---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  annotations:
    ves.io/proxy-type: HTTP_PROXY
  labels:
    app: nginx-app
    svc_name: nginx-app
spec:
  type: ClusterIP
  selector:
    app: nginx-app
  ports:
    - name: nginx-app
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-app
          image: public.ecr.aws/r2r2l6v3/f5-labs:nginx-unprivileged
          ports:
            - containerPort: 8080